name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show toolchain
        run: |
          xcodebuild -version
          swift --version

      - name: Build CLI
        run: make build
